Homepage/urls.py
from django.urls import path,include
from . import views

#<a href="/lecture/{{note.note.title}}/{{ note.note.id }}"> hard to change
#<a href="{%url 'S&S:lecture' note.note.title note.note.id %}"

#GET /input=652&input=ssss
#POST / 
app_name='S&S'
urlpatterns = [
    path('', views.home, name='home'), # new
    path('accounts/', include('django.contrib.auth.urls')), 
    path('signup/', views.signup, name='signup'),
    path('change-password/', views.change_password, name='change_password'),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('upload/',views.upload,name='upload'),
    path('lecture/<str:lecture_title>/<int:lecture_id>/', views.lecture, name='lecture'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

sandslecture/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Homepage.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler500='Homepage.views.handler500'

Homepage/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Profile(models.Model): #It use to identify person (who is post or save this note)
    #user is link to User(Model by Django) #One User One profile
    user = models.OneToOneField(
        User, on_delete=models.CASCADE,
        blank=True, default=None, null=True
        )

    #profile_picture 
    #Your can find it in Homepage/media/images
    profile_picture = models.ImageField(
        upload_to="images/", blank=True,
        default=None, null=True
        ) 
    
    #It show username when something call class Profile
    def __str__(self):
        return self.user.username

class Lecture(models.Model): #It is collect a content of note
    title = models.CharField(max_length=200, null=True ,blank=True)

    subject = models.CharField(max_length=200, null=True)

    description = models.CharField(max_length=2000, null=True)

    #author #It is link to Profile Class(It can be many Lecture on one Profile) 
    #!!!When use Check about Save()!!!
    #line(42-46)
    author = models.ForeignKey(
        Profile, related_name='author',
        on_delete=models.CASCADE, blank=True,
        null=True
        )

    #user_saved 
    #Ex Time(user 1) and Ace(user 2) are save C++ note and python note 
    #   user_saved(C++ note)have 2 Profile(Time and Ace) and Profile(Time)have 2 user_saved(C++ note and python note)
    # !!!When use Check about Save() !!!
    #There are many objects created. May be confused in order and adding models later.
    #Ex I create One Lecture ,I'am save() or save(commit=False) to create a Lecture_image but don't save() again 
    #   Server run pass Until when create a lecture we will know that it is Error if we don't use testing in Django
    user_saved = models.ManyToManyField(Profile) 

    #It show title when something call class Lecture
    def __str__(self):
        return self.title

class Lecture_image(models.Model):#It is collect a content picture on note

    #lecturekey 
    # It is link to Lecture Class(It can be many Lecture_image on one Lecture) 
    # !!!When use Check about Save() (line 42-44) !!!
    lecturekey = models.ForeignKey(
        Lecture, related_name='Lecture_image',
        on_delete=models.CASCADE, blank=True,
        null=True
        )

    image = models.ImageField(upload_to='lecture_image', )

    #It show name of image file when something call class Lecture_image
    def __str__(self):
        return self.image.name
    
class Rate(models.Model):
    user_rate=models.ForeignKey(Profile,
        on_delete=models.CASCADE, blank=True,
        null=True
        )
    lecture_rate=models.ForeignKey(Lecture,
        on_delete=models.CASCADE, blank=True,
        null=True
        )
    comment=models.CharField(max_length=1000,blank=True,
        null=True)
    rate=models.IntegerField(blank=True,
        null=True)

class ErrorReport(models.Model):
    error_views = models.CharField(max_length=100, null=True)
    error_detail = models.CharField(max_length=1000, null=True)
    error_massage_to_user= models.CharField(max_length=1000, null=True)

    

Homepage/forms.py
from django.forms import ModelForm
from .models import Profile,Lecture,Lecture_image

# Create the form class.
class Profileform(ModelForm):
     class Meta:
        model = Profile
        fields = ['profile_picture']

class LectureForms(ModelForm):
   class Meta:
      model = Lecture
      fields = ['title','description']

class Lecture_imgForms(ModelForm):
      class Meta:
         model = Lecture_image
         fields = ['image']

Homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm , PasswordChangeForm
from django.contrib.auth import logout, authenticate, login , update_session_auth_hash
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse
from django.forms import modelformset_factory
from django.http import Http404
from django.db.models import Count
from django.contrib import messages
from .forms import Profileform,LectureForms
from .models import Lecture,Profile,Lecture_image,Rate,ErrorReport
from django.urls import reverse

class NoteWithThumbnail:#It is use college example note (Show about title,example picture,author)

    def __init__(self, note, thumbnail):
        self.note = note
        self.thumbnail = thumbnail



#views area
def handler500(request):
    error_report=ErrorReport.objects.order_by('-id')[0]
    return render(request, 'error_500.html',{'error_massage':error_report.error_massage_to_user, 
        'error_views':error_report.error_views})

def signup(request):
    if request.method == 'POST':
        # Django forms
        newuserforms = UserCreationForm(request.POST)       
        if newuserforms.is_valid():
            try:
                newuser = newuserforms.save()
                username = newuserforms.cleaned_data.get('username')
                raw_password = newuserforms.cleaned_data.get('password1')
                Profile.objects.create(user=newuser)
                # (authenticate)It verify a new user created 
                # is valid(retune User object) or isn't valid(return None)
                user = authenticate(username=username, password=raw_password)
                # use user(User object that returned) to log in
                login(request, user) 
                return redirect(reverse("S&S:login")) #redirect('/')
            except:
                ErrorReport.objects.create(error_views="sign up", error_detail="user form",
                    error_massage_to_user="Username or Password isn't valid")
    else:
        newuserforms = UserCreationForm()
    return render(request, 'signup.html', {'newuserforms': newuserforms})

def home(request):
    noteWithThumbnail = []
    latest_note = []
    popular_note = []
    # a conditional check Is there search?
    if request.GET.get('keyword_search'):
        #keyword_search is input
        keyword = request.GET.get('keyword_search').lower()
        try:
            for note in Lecture.objects.all():
                if (keyword in note.title.lower() or keyword in note.description.lower() or note.Lecture_image.all()):
                    noteWithThumbnail.append(NoteWithThumbnail(note, note.Lecture_image.all()[0]))
            return render(request, 'searchresult.html', {'noteWithThumbnail':noteWithThumbnail})
        except:
            ErrorReport.objects.create(error_views="home", error_detail="search", 
                error_massage_to_user="Try enter your word to search again")
    else:
        try:
            #It use to Show 8 lastest note 
            #order_by(-id) is return object ordered by id descending 
            #but really shouldn't [::-1]
            for note in Lecture.objects.all().order_by('-id')[:8][::-1]:
                if note.Lecture_image.all():
                    latest_note.append(NoteWithThumbnail(note, note.Lecture_image.all()[0]))
        except:
            ErrorReport.objects.create(error_views="home", error_detail="lastest_note", 
                error_massage_to_user="Problem about note")
        try:
            #It use Show 8 most saved note
            #annotate(count=Count('userSaved')) It use to count each Lecture object
            for note in Lecture.objects.annotate(count=Count('user_saved')).order_by('count')[:8][::-1]:
                if note.Lecture_image.all():
                    popular_note.append(NoteWithThumbnail(note, note.Lecture_image.all()[0]))
            return render(request, 'home.html', {'latest_note': latest_note, 'popular_note': popular_note})
        except:
            ErrorReport.objects.create(error_views="home", error_detail="popular_note", 
                error_massage_to_user="Problem about note")


def upload(request):
    try:
        profile_obj = Profile.objects.get(user=request.user)
        if request.method == 'POST':
            lecture_forms = LectureForms(request.POST)
            if lecture_forms.is_valid() and request.FILES.get('image'):
                try:
                    lecture_forms = lecture_forms.save(commit=False)
                    lecture_forms.author = profile_obj
                    lecture_forms.save()
                    try:
                        # use loop to send output value(The input can Receive multiple image)
                        for i in request.FILES.getlist('image'):
                            photo = Lecture_image.objects.create(lecturekey=lecture_forms, image=i)
                            photo.save()
                        # redirect to homepage
                        return redirect(reverse("S&S:home"))
                    except:
                        ErrorReport.objects.create(error_views="upload", error_detail="object file image", 
                            error_massage_to_user="Files isn't valid")

                except:
                    ErrorReport.objects.create(error_views="upload", 
                        error_detail="Title or Description isn't valid")
            else:
                choose_files_message='Please choose files'
                    
        else:
            lecture_forms = LectureForms()
            choose_files_message=""
        return render(request, 'upload.html', {'lecture_forms': lecture_forms, 
            'choose_files_message':choose_files_message})
    except:
        ErrorReport.objects.create(error_views="upload", error_detail="Profile object", 
            error_massage_to_user="Problem about profile")

def change_password(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pass_change_forms = PasswordChangeForm(data=request.POST, user=request.user)
            if pass_change_forms.is_valid():
                try:
                    pass_change_forms.save()
                    #It user to update user object which the new session will be derived and updates the session appropriately
                    #session can temporarily store information like cookie
                    try:
                        update_session_auth_hash(request, pass_change_forms.user)
                        messages.success(request, 'Your password was successfully updated!')
                        return redirect(reverse("S&S:change_password"))
                    except:
                        ErrorReport.objects.create(error_views="change password", error_detail="update_session_auth_hash", 
                            error_massage_to_user="Proble about update password")
                except:
                    ErrorReport.objects.create(error_views="change password", error_detail="pass_change_forms", 
                        error_massage_to_user="Problem about old password or new password isn't valid")
        else:
            pass_change_forms = PasswordChangeForm(user=request.user) 
        return render(request, 'change_password.html', {'pass_change_forms': pass_change_forms})
    else:
        return redirect(reverse("S&S:login"))

def about(request):
    return render(request, 'about.html')

def help(request):
    return render(request, 'help.html')



def lecture(request, lecture_title, lecture_id):
    #it use to save note
    #<QueryDict:{}>
    #<QueryDict:{"{% csrf_token %}":fuenfekfhe ,"save_note":[]}>
    if (request.method == 'POST' and "save_note" in request.POST):
        try:
            profile_obj = Profile.objects.get(user=request.user)
        except:
            ErrorReport.objects.create(error_views="lecture", error_detail="profile objects", 
                error_massage_to_user="Problem about your profile")
        try:
            note_obj = Lecture.objects.get(id=int(request.POST.get('save_note')))
            #Check if user have saved it.
            if profile_obj not in note_obj.user_saved.all():
                note_obj.user_saved.add(profile_obj)
                note_obj.save()
            return HttpResponseRedirect(reverse('S&S:lecture',args=[note_obj.title,note_obj.id]))
        except:
            ErrorReport.objects.create(error_views="lecture", error_detail="note objects", 
                error_massage_to_user="Problem about this note")
    else:
        profile=None
        if request.user.is_authenticated:
            profile=Profile.objects.get(user=request.user)
        try:
            note_obj = Lecture.objects.get(id=lecture_id)
            #Check title match url
            if (note_obj.title!=lecture_title):
                error_massage = "Please check url or lecture will be delete"
                return render(request,"page_not_found.html",{"error_massage":error_massage})
            image_obj_list = note_obj.Lecture_image.all()
            #confirm is a varible,It use to consider that now is in delete_note form or confirm_delete_note form
            #confirm = False meaning now is in delete_note form
            confirm = False
            comment = False
            rate_list=[]
            total_point=0
            try:
                #"delete_note" is a name in botton
                if ( request.method == 'POST' and "delete_note" in request.POST):
                    #confirm = True meaning now is in confirm_delete_note form
                    confirm = True
                #"confirm_delete_note" is a name in botton
                elif (request.method == 'POST' and "confirm_delete_note" in request.POST):
                    #Delete all Lecture_imge of Lecture object
                    image_obj_list.delete()
                    #Delete this one Lecture object 

Homepage/templates/about.html
{% extends 'base.html' %}
{% block title %}S&SLecture About{% endblock %}
{% block content %}


<div  style="width: 800px; padding-top: 20px; margin: auto;">
    <br>
    <br>
    <h1>S&S Lecture</h1>
    <hr>
    <br>
    <p class="w3-xlarge">S&S Lecture หรือ Save and Share Lecture เป็นเว็บไซต์ที่ใช้สำหรับแชร์โน้ตหรือสรุปบทเรียนต่าง ๆ
        ซึ่งผู้ใช้งานสามารถเข้าไปอ่านหรือแชร์โน้ตของตัวเองในเว็บได้ รวมถึงการบันทึกโน้ตที่ชื่นชอบ
        เพื่อสามารถกลับมาอ่านโน้ตนั้นได้ตลอดเวลาโดยไม่ต้องเสียเวลาสำหรับการค้นหาครั้งใหม่</p>
    <p class="w3-xlarge">เนื่องจากสามารถแลกเปลี่ยนความรู้หลากหลายวิชาโดยไม่จำกัด
        ทำให้เว็บไซต์ของเราจึงเปรียบเสมือนสังคมแลกเปลี่ยนการเรียนรู้ขนาดย่อม ๆ ที่ไม่ว่าคุณจะอยู่ที่ไหน เวลาไหน
        ก็สามารถที่จะเปิดเข้าไปดูโน้ตได้ตลอดเวลา</p>
</div>

<div  style="width: 800px; padding-top: 20px; margin: auto;">
    <br>
    <br>
    <h1>Member</h1>
    <hr>
    <br>
    <p class="w3-xlarge">6101012610029 นายก้องภพ รักรุ่งโรจน์</p>
    <p class="w3-xlarge">6101012610070 นายบุริศร์ ฉายศิริ
    </p>
    <p class="w3-xlarge">6101012630046 นางสาวจินตปาตี สรวิเชียร
    </p>
    <p class="w3-xlarge">6101012630101 นายธีรภัทร ปรุงวัฒนากร
    </p>

</div>

{% endblock %}

Homepage/templates/base.html
<!-- templates/base.html -->
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&effect=brick-sign">


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>{% block title %}S&SLecture{% endblock %}</title>
</head>

<body style="padding-top: 70px;">
  <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #b7d5f1;">
    <a class="navbar-brand" href="{% url 'S&S:home' %}">
      <img src='{% static "/Homepage/logo.png" %}' width="45" height="45" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'S&S:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:about' %}" id="about">About</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:upload' %}" id="navbar_upload">Upload</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:profile' user.username %}" id="navbar_username">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:logout' %}" id="navbar_logout">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:login' %}" id="navbar_upload">Upload</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'S&S:login' %}" id="navbar_login">Login</a>
        </li>
        {% endif %}

      </ul>
      <form action="/" class="form-inline my-2 my-lg-0">
        <input name="keyword_search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button name="button_search" class="btn btn-outline-primary" type="submit">Search</button>
      </form>

      <a class="nav-link" href="{% url 'S&S:help' %}" id="help" text-align="navbar-right">
        <svg class="bi bi-info-circle" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z"
            clip-rule="evenodd" />
          <path
            d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z" />
          <circle cx="8" cy="4.5" r="1" />
        </svg>
      </a>

    </div>
  </nav>


  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  {% block content %}

  {% endblock %}


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

Homepage/templates/change_password.html
{% extends 'base.html' %}
{% block title %}S&SLecture Change-Password{% endblock %}

{% block content %}

<div class="col-md-5">
    <br>
    <br>
    <h2>Change-Password</h2>
    <hr>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ pass_change_forms.as_p }}
        <button class="btn btn-outline-primary"  type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

Homepage/templates/commentCardTem.html
<div class="row">
    {% for detail in ratedetail %}
    <div class=".col-xs-{{cardSize|default:'1'}}">
        <div class="card mb-4 box-shadow">

            <div class="card-body">
               
                <h6 class="card-title" id="latest_note{{ forloop.counter }}">{{ detail.comment }}</h4>
               

                <p style="transform: rotate(0);">
                    <a class="subinfo__author stretched-link" href="{% url 'S&S:profile' detail.user_rate %}">
                        {% if detail.user_rate.profile_picture %}
                        <img class="subinfo__author__img" alt="image not found"
                            style="vertical-align: middle; width: 50px; height: 50px; border-radius: 50%;"
                            src="{{ detail.user_rate.profile_picture.url }}">
                        {% else %}
                        <img class="subinfo__author__img" alt="image not found"
                            style="vertical-align: middle; width: 50px; height: 50px; border-radius: 50%;"
                            src="https://genslerzudansdentistry.com/wp-content/uploads/2015/11/anonymous-user.png">
                        {% endif %}
                        <span class="subinfo__author__name">{{ detail.user_rate }}</span>
                    </a>
                </p>

                <p class="card-text">{{ detail.rate }}Point</p>


            </div>
        </div>
    </div>
    {% endfor%}
</div>

Homepage/templates/error_500.html
<h1>Server error</h1>
<h2>{{error_massage}}</h2>
<h2>The officer has already received the issue. Please wait</h2>
<h2>The website will be working soon</h2>
{% if error_views != "home"  %}
<a href="/">
    <button>Go to home page</button>
</a>
{% endif %}

Homepage/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}S&SLecture Home{% endblock %}

{% block content %}
<div id="HomepageMainArea" >
    <div class="album py-5 bg-light">
        <div class="container">

            <div class="main">
                <i class="fa fa-trophy"></i>
                <h1>Popular</h1>
                <hr>
                <br>
            </div>

            {% include "noteCardTem.html" with noteObjList=popular_note only %}
        </div>
    </div>



    <div class="album py-5 bg-light">
        <div class="container">

            <div class="main">
                <i class="fa fa-trophy"></i>
                <h1>Lastest</h1>
                <hr>
                <br>
            </div>

            {% include "noteCardTem.html" with noteObjList=latest_note only %}
        </div>
    </div>

</div>
{% endblock %}

Homepage/templates/page_not_found.html
<h1>Page not found</h1>
<h3>{{error_massage}}</h3>
<a href="/">
    <buttom>Go to home page</buttom>
</a>

Homepage/templates/searchresult.html
{% extends 'base.html' %}
{% load static %}

{% block title %}S&SLecture Home{% endblock %}

{% block content %}
<div id="SearchResultPageMainArea">
    <div class="album py-5 bg-light">
        <div class="container">

            <div class="main">
                <i class="fa fa-trophy"></i>
                <h1>Search Result</h1>
                <hr>
                Found {{ noteWithThumbnail|length }} matches within titie or description
                <br>
            </div>

            {% include "noteCardTem.html" with noteObjList=noteWithThumbnail only %}
        </div>
    </div>
</div>
{% endblock %}

Homepage/templates/upload.html
{% extends 'base.html' %}

{% block title %}S&SLecture Profile{% endblock %}
{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<form action="" method="post" id="myForm" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="UploadpageMainArea">
        <div class="container login-container">
            <div class="row">

                <div class="col-md-offset-5 col-md-8 text-center">
                    <div class="input-group mb-3">
                        <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
                        <div class="container">
                            <fieldset class="form-group">
                                <tr>
                                    <th><label for="id_image">Image:</label></th>
                                    <td><input type="file" name="image" accept="image/*" id="id_image" multiple></td>
                                    <h5>{{choose_files_message}}</h5>
                                </tr>
                            </fieldset>
                            <div class="preview-images-zone"></div>
                            <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
                        </div>
                        
                    </div>
                </div>


                <div class="col-md-offset-5 col-md-4 text-center">
                    <br><br>
                    <h2>Upload</h2>
                    <div class="text-left">

                        <tr>
                            <th><label for="id_title">Title:</label></th>
                            <td><input type="text" class="form-control input-sm chat-input" name="title" maxlength="200"
                                    required id="id_title"></td>
                        </tr>
                        <br>
                        <tr>
                            <th><label for="id_description">Description:</label></th>
                            <td><input type="text" class="form-control input-sm chat-input" name="description"
                                    maxlength="2000" required id="id_description"></td>
                        </tr>
                        <br>
                    </div>

                    <div class="text-center">
                        <input type="submit" class="btn btn-outline-primary" name="submitbutton" id="submitbutton" value="Submit">
                    </div>
                </div>
</form>

<script>
    $(document).ready(function () {
        document.getElementById('id_image').addEventListener('change', readImage, false);

        $(".preview-images-zone").sortable();

        $(document).on('click', '.image-cancel', function () {
            let no = $(this).data('no');
            $(".preview-image.preview-show-" + no).remove();
        });
    });



    var num = 4;
    function readImage() {
        if (window.File && window.FileList && window.FileReader) {
            var files = event.target.files; //FileList object
            var output = $(".preview-images-zone");

            for (let i = 0; i < files.length; i++) {
                var file = files[i];
                if (!file.type.match('image')) continue;

                var picReader = new FileReader();

                picReader.addEventListener('load', function (event) {
                    var picFile = event.target;
                    var html = '<div class="preview-image preview-show-' + num + '">' +
                        '<div class="image-cancel" data-no="' + num + '">x</div>' +
                        '<div class="image-zone"><img id="pro-img-' + num + '" src="' + picFile.result + '"></div>';

                    output.append(html);
                    num = num + 1;
                });

                picReader.readAsDataURL(file);
            }
        } else {
            console.log('Browser not support');
        }
    }
</script>

<style>
    .preview-images-zone {
        width: 100%;
        border: 1px solid #ddd;
        min-height: 180px;
        /* display: flex; */
        padding: 5px 5px 0px 5px;
        position: relative;
        overflow: auto;
    }

    .preview-images-zone>.preview-image:first-child {
        height: 300px;
        width: 300px;
        position: relative;
        margin-right: 5px;
    }

    .preview-images-zone>.preview-image {
        height: 90px;
        width: 90px;
        position: relative;
        margin-right: 5px;
        float: left;
        margin-bottom: 5px;
    }

    .preview-images-zone>.preview-image>.image-zone {
        width: 100%;
        height: 100%;
    }

    .preview-images-zone>.preview-image>.image-zone>img {
        width: 100%;
        height: 100%;
    }
    
    .preview-images-zone>.preview-image>.image-cancel {
        font-size: 18px;
        position: absolute;
        top: 0;
        right: 0;
        font-weight: bold;
        margin-right: 10px;
        cursor: pointer;
        display: none;
        z-index: 100;
    }

    .preview-image:hover>.image-zone {
        cursor: move;
        opacity: .5;
    }

    .preview-image:hover>.image-cancel {
        display: block;
    }

    .ui-sortable-helper {
        width: 90px !important;
        height: 90px !important;
    }

    .container {
        padding-top: 50px;
    }
</style>


{% endblock %}